FROM registry-jinan-lab.inspurcloud.cn/library/os/ubuntu-1604-mips64el:5.0.0 AS release
ARG TARGETARCH=mips64le
COPY collector-linux-$TARGETARCH /go/bin/collector-linux
EXPOSE 14250/tcp
ENTRYPOINT ["/go/bin/collector-linux"]
