FROM registry-jinan-lab.inspurcloud.cn/library/os/ubuntu-1604:5.0.0 AS release
ARG TARGETARCH=amd64
COPY collector-linux-$TARGETARCH /go/bin/collector-linux
EXPOSE 14250/tcp
ENTRYPOINT ["/go/bin/collector-linux"]
