FROM registry-jinan-lab.inspurcloud.cn/library/os/ubuntu-1604-mips64el:5.0.0 AS release
ARG TARGETARCH=mips64el
COPY query-linux-$TARGETARCH /go/bin/query-linux
EXPOSE 16686/tcp
ENTRYPOINT ["/go/bin/query-linux"]
